---
version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - code-server-config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

volumes:
    code-server-config: