apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-duckdns
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-06-17T15:09:21Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-duckdns
    spec:
      containers:
      - env:
        - name: LOG_FILE
          value: "true"
        - name: PGID
          value: "1001"
        - name: PUID
          value: "1001"
        - name: SUBDOMAINS
          value: mendoj-test,mendoj-vpn
        - name: TOKEN
          value: 486019ff-b7f5-4ed5-a1da-cd3695f7f668
        - name: TZ
          value: America/New York
        image: linuxserver/duckdns
        imagePullPolicy: Always
        name: duckdns
        volumeMounts:
        - mountPath: /config
          name: duckdns
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/ubuntu/duckdns/config
          type: ""
        name: duckdns
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-06-17T15:09:35Z"
    lastUpdateTime: "2021-06-17T15:09:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-06-17T15:09:23Z"
    lastUpdateTime: "2021-06-17T15:09:35Z"
    message: ReplicaSet "duckdns-84cffc8dfc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
