version: "2.4"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - plex-config:/config
      - /media/plex:/plex
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - sonarr-config:/config
      - /media/plex:/plex
      - /home/ubuntu/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - radarr-data:/config
      - /media/plex:/plex
      - /home/ubuntu/torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - jackett-config:/config
      - /home/ubuntu/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr
    restart: unless-stopped
    ports:
        - 90:80
    volumes:
        - organizr-config:/config
    environment:
        - fpm=true #true or false | using true will provide better performance
        - branch=v2-master #v2-master or #v2-develop
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
        
  qbittorrentvpn:
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    container_name: qbittorrentvpn
    # privileged: true   
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=email
      - OPENVPN_PASSWORD=pass
      - NORDVPN_COUNTRY=US
      - PUID=1000
      - PGID=1000
      - LAN=192.168.0.0/16
      - NAME_SERVERS=8.8.8.8,8.8.4.4 #you can use whatever DNS provider you want
    ports:
      - 8080:8080
    volumes:
      - /home/ubuntu/media-configs/qbittorrentvpn-config:/config
      - /home/ubuntu/torrents:/downloads
      - /etc/timezone:/etc/timezone:ro #This is for TimeZone
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  

## System Monitoring

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
        - UMASK_SET=022
      volumes:
        - /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml 
      ports:
        - 9292:9090
      restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
    volumes:
      - /:/host:ro,rslave
    ports:
      - 9100:9090
    restart: unless-stopped
  
grafana:
  image: grafana/grafana
  container_name: grafana
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    - UMASK_SET=022
  ports:
    - 3000:3000
  restart: unless-stopped

# volumes:
#   plex-config:
#   sonarr-config:
#   radarr-config:
#   jackett-config: