apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-data
  namespace: pihole
  labels:
    type: nfs
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/k8s
    server: 192.168.1.223

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec: 
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - env:
        - name: DNS1
          value: 8.8.8.8
        - name: DNS2
          value: 8.8.4.4
        - name: TZ
          value: America/New York
        image: pihole/pihole:latest
        imagePullPolicy: Always
        name: pihole
        ports:
        - containerPort: 53
          hostPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 80
          hostPort: 8001
          name: pihole-http
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole-data
        - mountPath: /etc/dnsmasq.d
          name: pihole-data
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: pihole-data
        
---

apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  ports:
  - port: 8001
    protocol: TCP
  selector:
    app: pihole