apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodbport
  # externalIPs:
  #   - 192.168.1.223
  type: LoadBalancer

